services:
  gc_prod_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc_prod_api
    env_file: .env
    restart: always
    networks:
      - gc_production_network
      - monitoring
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        labels: "service=gc_prod_api"
        loki-timeout: "2s"
        loki-retries: "3"
        loki-batch-wait: "1s"
    stop_grace_period: 10s

  gc_preprod_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc_preprod_api
    env_file: .env
    restart: always
    networks:
      - gc_preprod_network
      - monitoring
      - proxy
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        labels: "service=gc_preprod_api"
        loki-timeout: "2s"
        loki-retries: "3"
        loki-batch-wait: "1s"
    stop_grace_period: 10s

networks:
  gc_preprod_network:
    external: true
  gc_production_network:
    external: true
  monitoring:
    external: true
  proxy:
    external: true