name: Checks

on:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: mysql://user:password@127.0.0.1:3306/gc

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    services:
      mysql:
        image: mariadb:11.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gc
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping -h 127.0.0.1 -u user -ppassword" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Security Audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,mysql

      - name: Seed Database
        run: mysql -h 127.0.0.1 -u user -ppassword gc < import.sql

      - name: Install cargo-clippy
        run: rustup component add clippy

      - name: Run Clippy SAST
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test --verbose